# nginx.conf — Angular SPA
# Todas las rutas desconocidas redirigen a index.html para que
# Angular Router gestione la navegación en cliente.

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
