# nginx.conf — 11ty sitio estático
# 11ty genera /ruta/index.html, nginx sirve el directorio directamente.

server {
    listen ${PORT};
    listen [::]:${PORT};
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
